version: 0.2

phases:
  pre_build:
    commands:
      # Auth with ECR
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

      #- echo Logging in to Amazon ECR...
      #- aws --version
      #- aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_NAME:${CODEBUILD_RESOLVED_SOURCE_VERSION} .
      - docker tag $ECR_NAME:${CODEBUILD_RESOLVED_SOURCE_VERSION}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $ECR_NAME:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker push $ECR_NAME:${CODEBUILD_RESOLVED_SOURCE_VERSION}:latest